Rails.application.routes.draw do
  root 'static_pages#home'
  get     '/help',     to: 'static_pages#help'
  get     '/about',    to: 'static_pages#about'
  get     '/contact',  to: 'static_pages#contact'
  get     '/signup',   to: 'users#new'
  post    '/signup',   to: 'users#create'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  resources :users do #endows the application with all the actions needed for a RESTful Users Resouce
    member do
      get :following, :followers
    end
  end
  # routes generated by get :follwing, :followers 
  # GET - /users/1/following - following - following_user_path(1)
  # get - /users/1/followers - followers - followers_user_path(1)

  # create a named RESTful route for the EDIT action: 
  # HTTP request: GET, URL: /account_activation/<token>/edit, Action: EDIT
  # named RESTful route: edit_account_activation_url(token)
  resources :account_activations, only: [:edit] 

  # Need forms for creating new password resets and for updating them by changing the password
  # in the user model. So create routes for new, create, edit, and update through resources. 
  # HTTP REQUEST - URL - ACTION - NAMED ROUTE 
  # GET - /password_resets/new - new - new_password_reset_path
  # POST - /password_resets/create - create - create_password_reset_path
  # GET - /password_resets/<token>/edit - edit - edit_password_reset_path(token)
  # POST - /password_resets/<token> - update - update_password_reset_url(token)
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Interface to the Microposts resource will run mainly through Profile and Home pages
  # so there is only need for the create and destroy actions in the Microposts controller
  # POST - /microposts - create - microposts_path
  # DELETE - /microposts/1 - destroy - micropost_path(micropost)
  resources :microposts, only: [:create, :destroy]

  # POST - /relationships - create - relationships_path
  # DELETE - /relationships/1 - destroy - relationships_path(relationship)
  resources :relationships, only: [:create, :destroy]
end
